In [1]:
#pip install numpy 

In [1]:
#import the dependencies
import numpy as np

In [2]:
A = np.random.randn(4,3) 
B = np.sum(A, axis = 1, keepdims = True) 

B.shape

(4, 1)

## Creating an array

In [4]:
number = np.array([1,2,3,4,5])
print(number)

[1 2 3 4 5]


In [5]:
print(type(number))

<class 'numpy.ndarray'>


In [6]:
string = np.array(["sreet","avenue","city"])
print(string)

['sreet' 'avenue' 'city']


In [7]:
print(type(string))

<class 'numpy.ndarray'>


In [8]:
# sclicing
print(string[0:])

['sreet' 'avenue' 'city']


In [9]:
#indexing
print(string[2])

city


## Built in array function

In [11]:
# zeros function
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [16]:
# ones function
b = np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [15]:
# empty function
c = np.empty(5)
print(c)

[0. 0. 0. 0. 0.]


In [13]:
# range function
d = np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# sprcify
e = np.arange(1,20,2)
print(e)

[ 1  3  5  7  9 11 13 15 17 19]


In [17]:
# line space
f = np.linspace(1,500,num=50)
print(f)

[  1.          11.18367347  21.36734694  31.55102041  41.73469388
  51.91836735  62.10204082  72.28571429  82.46938776  92.65306122
 102.83673469 113.02040816 123.20408163 133.3877551  143.57142857
 153.75510204 163.93877551 174.12244898 184.30612245 194.48979592
 204.67346939 214.85714286 225.04081633 235.2244898  245.40816327
 255.59183673 265.7755102  275.95918367 286.14285714 296.32653061
 306.51020408 316.69387755 326.87755102 337.06122449 347.24489796
 357.42857143 367.6122449  377.79591837 387.97959184 398.16326531
 408.34693878 418.53061224 428.71428571 438.89795918 449.08163265
 459.26530612 469.44897959 479.63265306 489.81632653 500.        ]


In [2]:
# specify data type
b = np.ones(5,dtype=np.int64)
print(b)

[1 1 1 1 1]


## Array function

In [3]:
ab = np.array([12,17,19,16,14,17,29,25,21,20])
print(ab)

[12 17 19 16 14 17 29 25 21 20]


In [4]:
ab.sort()
print(ab)

[12 14 16 17 17 19 20 21 25 29]


In [11]:
ac = np.array([13,31,37,39,35,34,33])
print(ac)
ad = np.concatenate((ab,ac))
print(ad)
ad.sort()
print(ad)

[13 31 37 39 35 34 33]
[12 14 16 17 17 19 20 21 25 29 13 31 37 39 35 34 33]
[12 13 14 16 17 17 19 20 21 25 29 31 33 34 35 37 39]


## 2D-Array

In [13]:
number = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(number)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [14]:
number1 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(number1)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
nom = np.concatenate((number,number1), axis=1)
print(nom)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9  0 16 17 18 19 20]]


In [18]:
nom = np.concatenate((number,number1), axis=0)
print(nom)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
td = np.array([[[0,1,2,3,4],[5,6,7,8,9]],
               [[10,11,12,13,14],[15,16,17,18,19]],
               [[20,21,22,23,24],[25,26,27,28,29]]])
print(td)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [41]:
# indexing in 3d array
print(td[1][0][4])

14


In [21]:
print(nom.ndim)
print(td.ndim)

2
3


In [22]:
print(nom.size)
print(td.size)

20
30


In [23]:
print(nom.shape)
print(td.shape)

(4, 5)
(3, 2, 5)


In [30]:
# reshape
n = np.arange(9)
print(n)
print(n.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
# converting 1d into 2d array
h = np.array([1,2,3,4,5,6,7,8,9])
print(h)
print(h.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [34]:
k = h[np.newaxis, :]
print(k)
k = h[:,np.newaxis,]
print(k)

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
