# DecisionTree

In [4]:
# loading dataset
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [6]:
data = load_iris()
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
x = data.data
y = data.target

# Train Test Split

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

# Creating Model

In [10]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier().fit(x_train,y_train)
model

DecisionTreeClassifier()

# Prediction

In [14]:
pred = model.predict(x_test)
pred

array([0, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 1, 0, 0, 0])

# Accuracy

In [16]:
model.score(x_test,pred)

1.0

# Accuracy on 20% test

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [18]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier().fit(x_train,y_train)
model

DecisionTreeClassifier()

In [19]:
pred = model.predict(x_test)
pred

array([2, 0, 2, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 0, 1, 1, 1, 2, 2, 0,
       2, 1, 2, 1, 0, 0, 1, 1])

In [20]:
model.score(x_test,pred)

1.0

# Accuracy on 30% test

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [22]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier().fit(x_train,y_train)
model

DecisionTreeClassifier()

In [23]:
pred = model.predict(x_test)
pred

array([0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 2, 0, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0,
       1, 2, 0, 1, 0, 0, 2, 0])

In [24]:
model.score(x_test,pred)

1.0

# Predicting on Unknown Value

In [30]:
model.predict([[6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [3.3, 1.5, 4. , 2.9],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

array([2, 2, 2, 0, 0])